# O comando 'createDatabaseIfNotExist=true' cria o banco automaticamente pra você!
spring.datasource.url=

# 2. Usuário e Senha (Coloque os que você definiu na instalação do MySQL)
spring.datasource.username=root
spring.datasource.password=

# 3. Driver do MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. Configurações do Hibernate/JPA
# 'update' faz o Hibernate criar/alterar as tabelas sozinho baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console (ajuda muito a entender o que está acontecendo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto para o MySQL 8+
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect